name: Java CI with Maven

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Verify Maven Installation
        run: mvn -version

      - name: Build Project
        run: mvn clean package

      - name: Upload Dependency Graph
        uses: advanced-security/maven-dependency-submission-action@v5
